import { useState, useEffect } from 'react';
import { useLocation, useNavigate, Link } from 'react-router-dom';
import toast from 'react-hot-toast';
import api from '../../services/api';
import { useAuth } from '../../hooks/useAuth';
import { ShieldCheckIcon } from '@heroicons/react/24/outline';

export default function AdminTOTP() {
  const location = useLocation();
  const navigate = useNavigate();
  const { login } = useAuth();
  const [tempToken, setTempToken] = useState('');
  const [code, setCode] = useState('');
  const [loading, setLoading] = useState(false);

  useEffect(() => {
    const token = location.state?.tempToken;
    if (!token) {
      toast.error('Session expired. Please log in again.');
      navigate('/admin/login');
    } else {
      setTempToken(token);
    }
  }, [location, navigate]);

  const handleSubmit = async (e) => {
    e.preventDefault();
    if (code.length !== 6) return toast.error('Enter 6-digit verification code');
    setLoading(true);
    try {
      const res = await api.post('/admin/verify-totp', { tempToken, code });
      login(res.data.token, res.data.user, 'admin');
      toast.success('Admin login successful! Welcome back.');
      navigate('/admin/dashboard');
    } catch (err) {
      toast.error(err.response?.data?.message || 'Invalid verification code');
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="min-h-screen bg-provexa-bg flex items-center justify-center p-4">
      <div className="w-full max-w-sm">
        <div className="text-center mb-6">
          <Link to="/" className="text-xl font-black text-provexa-navy">🛡️ PROVEXA</Link>
        </div>
        <div className="bg-white rounded-2xl card-shadow p-8 text-center">
          <div className="flex justify-center mb-4">
            <div className="p-4 bg-red-50 rounded-full">
              <ShieldCheckIcon className="w-10 h-10 text-provexa-red" />
            </div>
          </div>
          <h1 className="text-xl font-bold text-gray-800 mb-2">Two-Factor Authentication</h1>
          <p className="text-sm text-gray-500 mb-6">
            Enter the 6-digit security code generated by your Authenticator app.
          </p>

          <form onSubmit={handleSubmit} className="space-y-4">
            <input
              type="text"
              value={code}
              onChange={e => setCode(e.target.value.replace(/\D/g, '').slice(0, 6))}
              className="input-field text-center text-2xl font-bold tracking-widest focus:ring-provexa-red"
              placeholder="000 000"
              maxLength={6}
              required
            />
            <button type="submit" disabled={loading || code.length !== 6} className="btn-primary w-full bg-provexa-red hover:bg-red-800">
              {loading ? 'Authenticating...' : 'Verify Security Code'}
            </button>
          </form>

          <Link to="/admin/login" className="block mt-4 text-xs text-gray-400 hover:text-gray-600">
            Cancel and Return
          </Link>
        </div>
      </div>
    </div>
  );
}
